export const hindiMovies = [
  {
    title: "Dangal",
    actor: "Aamir Khan",
    genre: "Biography, Drama, Sport",
    director: "Nitesh Tiwari",
    img: "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcS-eAZoxBzm-lW88kcC50log_jC7sBxwbsrx8Tvy3vRVLy-IF5r",
  },
  {
    title: "PK",
    actor: "Aamir Khan",
    genre: "Comedy, Drama, Fantasy",
    director: "Rajkumar Hirani",
    img: "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcQSSaD2bSPOgmgsn4-09dF2l8mHbuvHhJxbkL7rvD1uEpAxKnLX",
  },
  {
    title: "3 Idiots",
    actor: "Aamir Khan",
    genre: "Comedy, Drama",
    director: "Rajkumar Hirani",
    img: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcQSaAgEKGAhM-PkFO0PbwPvuttF3X7d0BlqMHAm5tTKQtPqIheT",
  },
  {
    title: "Bajrangi Bhaijaan",
    actor: "Salman Khan",
    genre: "Action, Adventure, Comedy",
    director: "Kabir Khan",
    img: "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcTqyS3fXzIKWbqk_VFlX9N88X7cZi4O4fw1mXdEj587eOlo1GF-",
  },
  {
    title: "Sultan",
    actor: "Salman Khan",
    genre: "Action, Drama, Sport",
    director: "Ali Abbas Zafar",
    img: "https://upload.wikimedia.org/wikipedia/en/1/1f/Sultan_film_poster.jpg",
  },
  {
    title: "Chennai Express",
    actor: "Shah Rukh Khan",
    genre: "Action, Adventure, Comedy",
    director: "Rohit Shetty",
    img: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcRcGEy2HE1cMaVD3t9ir_Ld7A5xb9723xGt3U12sIQaEI4_lBMF",
  },
  {
    title: "Dilwale Dulhania Le Jayenge",
    actor: "Shah Rukh Khan",
    genre: "Drama, Romance",
    director: "Aditya Chopra",
    img: "https://www.yashrajfilms.com/images/default-source/Movies/Dilwale-Dulhania-Le-Jayenge/Dilwale-Dulhania-Le-Jayenge-Gallery/shahrukh-khan-and-kajol-in-dilwale-dulhania-le-jayenge86f19da026f56f7f9f64ff0000090313.jpg",
  },
  {
    title: "Padmaavat",
    actor: "Deepika Padukone, Ranveer Singh, Shahid Kapoor",
    genre: "Drama, History, Romance",
    director: "Sanjay Leela Bhansali",
    img: "https://contentserver.com.au/assets/603892_v7_padvaati.jpg",
  },
  {
    title: "Queen",
    actor: "Kangana Ranaut",
    genre: "Adventure, Comedy, Drama",
    director: "Vikas Bahl",
    img: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcSynRf_A5zoCOM3VQp0R9V3yBGvGdtXOJHqDAfBOnCn2mWUnRo4",
  },
  {
    title: "Andhadhun",
    actor: "Ayushmann Khurrana, Tabu, Radhika Apte",
    genre: "Crime, Thriller",
    director: "Sriram Raghavan",
    img: "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcT-PKn3ieG8r0-z_5YKGpIiWXBbIrRHwxxkzWQwfVumxi7TGNn4",
  },
  {
    title: "Stree",
    actor: "Rajkummar Rao, Shraddha Kapoor",
    genre: "Comedy, Horror",
    director: "Amar Kaushik",
    img: "https://contentserver.com.au/assets/653486_stree_v8.jpg",
  },
  {
    title: "Gully Boy",
    actor: "Ranveer Singh, Alia Bhatt",
    genre: "Drama, Music",
    director: "Zoya Akhtar",
    img: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcRINw19ijLMjFU2nPMR1wmx_JW908AV5CShaEDZuu_RIZdQpwxr",
  },
  {
    title: "Kabir Singh",
    actor: "Shahid Kapoor, Kiara Advani",
    genre: "Action, Drama, Romance",
    director: "Sandeep Reddy Vanga",
    img: "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcSSBjgn6nmJttwcTh0nmdTxJLyomVapLaColnlJZ9dXLjf-Y1tP",
  },
  {
    title: "Ludo",
    actor:
      "Abhishek Bachchan, Rajkummar Rao, Aditya Roy Kapur, Pankaj Tripathi",
    genre: "Action, Comedy, Crime",
    director: "Anurag Basu",
    img: "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcTMVa41j75lbnd4VZcLLzl6L4eYKUBijJ8mQELU27AwJ4kLAND5",
  },
  {
    title: "Badhaai Ho",
    actor: "Ayushmann Khurrana, Neena Gupta, Gajraj Rao",
    genre: "Comedy, Drama",
    director: "Amit Sharma",
    img: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcTRwdILw-UcAN1DHNDZKMmaoiuA7O6LdqzP--Xq1QOiOXeLsiVs",
  },
];
